@php
// Tokens du design system ChillNet (base Stitch midnight navy)
@endphp
<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet" />
<link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" rel="stylesheet" />
<style>@layer base{html,body{margin:0;padding:0;}html{scroll-behavior:smooth;}body{overscroll-behavior:none;}main>:first-child{margin-top:0!important;}main>:last-child{margin-bottom:0!important;}}::-webkit-scrollbar{display:none;}[x-cloak]{display:none!important;}</style>
<script src="https://cdn.tailwindcss.com"></script>
<script id="tailwind-config">tailwind.config={darkMode:"class",theme:{extend:{colors:{"surface-variant":"#313540","on-tertiary-fixed-variant":"#604100","on-surface":"#dfe2f1","surface-bright":"#353944","surface-dim":"#0f131d","background":"#0f131d","on-error":"#690005","on-primary-container":"#00626e","tertiary":"#ffe9cd","inverse-surface":"#dfe2f1","primary-fixed":"#9cf0ff","inverse-on-surface":"#2c303b","primary-container":"#00e5ff","secondary-container":"#0566d9","on-primary-fixed":"#001f24","on-tertiary":"#432c00","surface-container":"#1c1f2a","surface":"#0f131d","primary-fixed-dim":"#00daf3","on-background":"#dfe2f1","secondary-fixed":"#d8e2ff","on-secondary":"#002e6a","outline-variant":"#3b494c","surface-container-highest":"#313540","inverse-primary":"#006875","on-tertiary-container":"#775200","on-surface-variant":"#bac9cc","tertiary-container":"#ffc769","secondary-fixed-dim":"#adc6ff","on-primary":"#00363d","surface-container-low":"#171b26","secondary":"#adc6ff","on-secondary-container":"#e6ecff","on-tertiary-fixed":"#281900","surface-tint":"#00daf3","surface-container-high":"#262a35","surface-container-lowest":"#0a0e18","error-container":"#93000a","on-error-container":"#ffdad6","outline":"#849396","on-secondary-fixed":"#001a42","on-primary-fixed-variant":"#004f58","primary":"#c3f5ff","tertiary-fixed":"#ffdeac","on-secondary-fixed-variant":"#004395","error":"#ffb4ab","tertiary-fixed-dim":"#ffba38"},borderRadius:{DEFAULT:"0.25rem",lg:"0.5rem",xl:"0.75rem",full:"9999px"},spacing:{"gutter":"1rem","margin-md":"1.5rem","space-xl":"2.5rem","space-lg":"1.5rem","gutter-lg":"1.5rem","margin":"1rem","space-md":"1rem","space-xs":"0.25rem","margin-lg":"2.5rem","space-sm":"0.5rem"},fontFamily:{"headline-sm":["Inter"],"label-md":["Inter"],"body-lg":["Inter"],"body-sm":["Inter"],"label-sm":["Inter"],"headline-lg":["Inter"],"body-md":["Inter"],"title-md":["Inter"],"display-lg":["Inter"]},fontSize:{"headline-sm":["20px",{lineHeight:"28px",fontWeight:"600"}],"label-md":["13px",{lineHeight:"18px",fontWeight:"500"}],"body-lg":["16px",{lineHeight:"24px",fontWeight:"400"}],"body-sm":["12px",{lineHeight:"16px",fontWeight:"400"}],"label-sm":["11px",{lineHeight:"14px",fontWeight:"600"}],"headline-lg":["32px",{lineHeight:"40px",fontWeight:"600"}],"body-md":["14px",{lineHeight:"20px",fontWeight:"400"}],"title-md":["16px",{lineHeight:"24px",fontWeight:"600"}],"display-lg":["48px",{lineHeight:"56px",fontWeight:"700"}]}}}};</script>
